- name: Create Minio User group minio
  group:
    name: minio-user
    state: present

- name: Add the user minio
  ansible.builtin.user:
    name: minio-user
    group: minio-user
    shell: "/usr/sbin/nologin"
    comment: MinIO administration user

- name: Create a directory if it does not exist for MinIO volume mount
  ansible.builtin.file:
    path: "{{ minio.volume_bind }}"
    state: directory
    mode: '0777'